/**
 * @module formatters/textFormatter
 * Formats grouped tabs as plain text, one tab per line.
 * Simple and fast — no markup, no escaping needed.
 */

import { chunkProcess } from '../utils/chunker.js';
import { sanitizeUrl, truncate } from '../utils/sanitizer.js';

export class TextFormatter {
  /**
   * @param {import('../core/groupResolver.js').GroupedTabs} groupedTabs
   * @param {{ includeTitle?: boolean }} options
   * @returns {Promise<string>}
   */
  async format(groupedTabs, { includeTitle = true } = {}) {
    const lines = [];
    const now   = new Date().toLocaleString();
    const sep   = '─'.repeat(60);

    lines.push('EXPORTED FIREFOX TABS');
    lines.push(`Exported: ${now}`);
    lines.push(`Total: ${groupedTabs.all.length} tab(s)`);
    lines.push(sep);

    // Native groups
    for (const entry of Object.values(groupedTabs.groups)) {
      lines.push('', `[ GROUP: ${entry.meta.name.toUpperCase()} — ${entry.tabs.length} tabs ]`, '');
      await chunkProcess(entry.tabs, 100, (tab) => {
        lines.push(this._tabLine(tab, includeTitle), '');
      });
    }

    // Containers
    for (const entry of Object.values(groupedTabs.containers)) {
      lines.push('', `[ CONTAINER: ${entry.meta.name.toUpperCase()} — ${entry.tabs.length} tabs ]`, '');
      await chunkProcess(entry.tabs, 100, (tab) => {
        lines.push(this._tabLine(tab, includeTitle), '');
      });
    }

    // Ungrouped
    if (groupedTabs.ungrouped.length > 0) {
      lines.push('', `[ DEFAULT / UNGROUPED — ${groupedTabs.ungrouped.length} tabs ]`, '');
      await chunkProcess(groupedTabs.ungrouped, 100, (tab) => {
        lines.push(this._tabLine(tab, includeTitle), '');
      });
    }

    lines.push('', sep, 'Generated by Tab Exporter (Firefox Extension)');
    return lines.join('\n');
  }

  /**
   * @param {import('../core/tabCollector.js').TabRecord} tab
   * @param {boolean} includeTitle
   * @returns {string}
   */
  _tabLine(tab, includeTitle) {
    const safeUrl = sanitizeUrl(tab.url);
    if (includeTitle && tab.title) {
      return `${truncate(tab.title, 100)}\n  ${safeUrl}`;
    }
    return safeUrl;
  }
}
